### ISSUE TITLE
Comparison against GLIDE

### ISSUE THREAD

**Issue by MyUsernamee** [kakaobrain/minDALL-E#14]
Recently Open AI posted [GLIDE](https://github.com/openai/glide-text2im), a diffusion model made for generating images from text, much like DALL-E. 

Would it be possible to compare minDALL-E to GLIDE and put the results on the github?

Thank you in advance!

Also I have to say this is amazing!

**Comment by LeeDoYup** [comment]
Thanks for your good suggestion.   
I agree that the comparison would be possible as you mention, 
but we do not plan to compare minDALL-E with the GLIDE in this repository due to the hardness of fair comparison.
