### ISSUE TITLE
Amazing work; models CDN?

### ISSUE THREAD

**Issue by johnpaulbin** [kakaobrain/minDALL-E#5]
Hi there! Just want to quickly congratulate all the effort done in this project!

Will the models / tokenizers also be stored in Github's releases binary? It could be good as a backup / alternative.

**Comment by wbaek** [comment]
Thanks for your suggestion.

However, the minDALL-E model file size is greater than 4 GB.
It is larger than the file size limit(2 GB) supported by github.

Please note the following:
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries
