### ISSUE TITLE
complete images?

### ISSUE THREAD

**Issue by loboere** [kakaobrain/minDALL-E#8]
you can add a way to complete images, give you an image without completion.

**Comment by LeeDoYup** [comment]
Hello @loboere , Thanks for your interest in our project.

Could you add more detailed explanation about your issue?
Does your issue mean how to use minDALL-E for image completion, which predicts the remaining parts of a masked image?

**Comment by loboere** [comment]
exactly

**Comment by saehoonkim** [comment]
@loboere, this version doesn't include an image completion script, but it could be implemented by modifying the sampling script. You might be interested in the related issue #6. Thanks!
