### ISSUE TITLE
질문있습니다. 파인튜닝 중에 image 에 대한 text 가 들어가지 않는데요

### ISSUE THREAD

**Issue by raki-1203** [kakaobrain/minDALL-E#9]
transfer_learning_ex.py 코드를 봤습니다 :)

파인튜닝 중에 image 에 대한 text 가 따로 들어가지 않아 보이는데요

image 에 대한 text 로 폴더명이 쓰이는 걸까요?

잘 만들어주셔서 감사합니다.

**Comment by saehoonkim** [comment]
현재 코드에서는 text와 image 쌍에 대한 파인튜닝 학습 예제는 없습니다. 대신에, 말씀해주신 코드는 transfer learning 예시로서 text-to-image 생성과 다른 태스크에서도 잘 동작하는 지 테스트하기 위한 목적입니다. 따라서, text가 따로 들어가지 않는 class-condition과 uncondition 생성 테스크에 대한 예시만 있습니다. 추가적인 문의 사항 있으시면 언제든지 말씀 부탁드립니다.

감사합니다!

**Comment by sangmandu** [comment]
@saehoonkim
안녕하세요, 질문드립니다.

text-to-image에 대한 transfer learning이 아예 불가한건가요? 아니면, 예제만 없다고 이해하면 되나요??
만약 가능하다면, 코드의 `ImageNetDataModule` 쪽을 수정하면 될까요?

감사합니다.

**Comment by saehoonkim** [comment]
@sangmandu text-to-image에 대한 transfer learning도 가능합니다. 코드의 ImageNetDataModule을 참고하셔서 text-image가 쌍으로 주어진 경우를 처리할 수 있도록 Dataset 모듈을 새롭게 구현하시면 됩니다. 감사합니다!

**Comment by j-min** [comment]
@saehoonkim 
안녕하세요. 혹시 text-to-image 학습 예제를 추가해 주실 계획이 있으신가요?
